# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - none*

changelog:
  sort: asc

brews:
  - tap:
      owner: dbirks
      name: ssmsh
    description: A shell for the EC2 Parameter Store
    homepage: https://github.com/bwhaley/ssmsh
    license: MIT
