# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ssmsh < Formula
  desc ""
  homepage ""
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/dbirks/ssmsh/releases/download/v0.0.2/ssmsh_0.0.2_darwin_amd64.tar.gz"
    sha256 "73b8f493595969ff131917f256400a5ca1e3e879fffa882b15930462ff682688"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/dbirks/ssmsh/releases/download/v0.0.2/ssmsh_0.0.2_linux_amd64.tar.gz"
    sha256 "2d522e1e2eccd8a830480c9ab44884d92f121dae1e6d23ef6b8f9ddb75f120d6"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/dbirks/ssmsh/releases/download/v0.0.2/ssmsh_0.0.2_linux_arm64.tar.gz"
    sha256 "828e59af627e123445a85aa6c161f13cbdf5018eb67cb8a263d5bb2eca3a4d18"
  end

  def install
    bin.install "ssmsh"
  end
end
